name = "SkyGraphTest"
uuid = "1d650cf3-e57c-4b77-b092-4d8c727dbaa3"
authors = ["Grant Regen <gregen@stanford.edu>", "Flynn Dreilinger <flynnd@stanford.edu>"]
version = "1.0.0-DEV"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
